spring.application.name=smart-campus-event-system
server.port=8080
# Default: H2 database for quick run. For MySQL, uncomment below and comment H2 section.
spring.datasource.url=jdbc:h2:mem:campusdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never

# MySQL settings example:
# spring.datasource.url=jdbc:mysql://localhost:3306/smart_campus_db?createDatabaseIfNotExist=true
# spring.datasource.username=root
# spring.datasource.password=
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Real email OTP: add your Gmail app password here.
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_email@gmail.com
spring.mail.password=your_16_digit_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.enabled=false
